routes/frontend.php
<?php
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\AuthController;

Route::get('/register', [AuthController::class, 'getRegister'])->name('home.get-register');
Route::post('/register', [AuthController::class, 'postRegister'])->name('home.post-register');
Route::get('/login', [AuthController::class, 'getLogin'])->name('home.get-login');
Route::get('/forgot-password', [AuthController::class, 'forgotPassword']);
Route::post('/login', [AuthController::class, 'postLogin'])->name('home.post-login');
Route::get('/logout', [AuthController::class, 'logout'])->name('home.logout');

Route::group(['middleware' => 'frontend'], function() {
    Route::get('/', [FrontendController::class, 'index'])->name('home.index');
    Route::get('/home/mbti', [FrontendController::class, 'mbti'])->name('home.mbti');
    Route::get('/home/leadership', [FrontendController::class, 'leadership'])->name('home.leadership');
    Route::get('/home/teamwork', [FrontendController::class, 'teamwork'])->name('home.teamwork');
    Route::get('/home/quick', [FrontendController::class, 'quick'])->name('home.quick');
    Route::get('/home/quick2', [FrontendController::class, 'quick2'])->name('home.quick2');
    Route::get('/home/result-quick', [FrontendController::class, 'resultQuick'])->name('home.quick.result');
    Route::get('/home/result', [FrontendController::class, 'resultMbti'])->name('home.mbti.result');
    Route::get('/home/result-leadership', [FrontendController::class, 'resultLeadership'])->name('home.leadership.result');
    Route::get('/home/result-teamwork', [FrontendController::class, 'resultTeamwork'])->name('home.teamwork.result');
    //end messenger
});

routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\CompanyController;

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::get('/admin', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('admin/user', UserController::class);
    Route::resource('admin/company', CompanyController::class);
    Route::resource('admin/roles', RoleController::class);
    Route::get('/admin/member/index', [MemberController::class, 'index'])->name('member.index');
    Route::delete('/admin/member/delete/{id}', [MemberController::class, 'destroy'])->name('member.destroy');
});

resources/views/backend/layouts/admin.blade.php
<!DOCTYPE html>
<html lang="en">
@include('backend.layouts.head')
<body class="hold-transition sidebar-mini layout-fixed">
    <div class="wrapper">
        <!-- Navbar -->
        @include('backend.layouts.header')
        <!-- /.navbar -->
        <!-- Main Sidebar Container -->
        @include('backend.layouts.sidebar')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper pt-2">
            <!-- Content Header (Page header) -->
            @yield('contentHeader')
            <!-- /.content-header -->

            <!-- Main content -->
            <section class="content">
                <div class="container-fluid">
                    @yield('content')
                </div>
            </section>
            <!-- /.content -->
        </div>
        <!-- /.content-wrapper -->
    </div>
    <!-- ./wrapper -->
    @include('backend.layouts.footer')
    @include('backend.layouts.mess')
    @yield('script')
</body>

</html>

resources/views/backend/layouts/footer.blade.php
<footer class="main-footer">
    <strong>Copyright &copy; 2021 <a href="https://ouransoft.vn">Ouransoft</a>.</strong>
    All rights reserved.
</footer>

<!-- Control Sidebar -->
<aside class="control-sidebar control-sidebar-dark">
    <!-- Control sidebar content goes here -->
</aside>
<!-- /.control-sidebar -->
</div>
<!-- ./wrapper -->

<script src={{ asset('AdminLTE/plugins/jquery/jquery.min.js') }}></script>
<!-- jQuery UI 1.11.4 -->
<script src={{ asset('AdminLTE/plugins/jquery-ui/jquery-ui.min.js') }}></script>
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
    $.widget.bridge('uibutton', $.ui.button)

</script>
<!-- Bootstrap 4 -->
<script src={{ asset('AdminLTE/plugins/bootstrap/js/bootstrap.bundle.min.js') }}></script>
<!-- ChartJS -->
<script src={{ asset('AdminLTE/plugins/chart.js/Chart.min.js') }}></script>
<!-- JQVMap -->
<script src={{ asset('AdminLTE/plugins/jqvmap/jquery.vmap.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/jqvmap/maps/jquery.vmap.usa.js') }}></script>
<!-- jQuery Knob Chart -->
<script src={{ asset('AdminLTE/plugins/jquery-knob/jquery.knob.min.js') }}></script>
<!-- daterangepicker -->
<script src={{ asset('AdminLTE/plugins/moment/moment.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/daterangepicker/daterangepicker.js') }}></script>
<!-- Tempusdominus Bootstrap 4 -->
<script src={{ asset('AdminLTE/plugins/tempusdominus-bootstrap-4/js/tempusdominus-bootstrap-4.min.js') }}>
</script>
<!-- overlayScrollbars -->
<script src={{ asset('AdminLTE/plugins/overlayScrollbars/js/jquery.overlayScrollbars.min.js') }}></script>
<!-- AdminLTE App -->
<script src={{ asset('AdminLTE/dist/js/adminlte.js') }}></script>
<!-- AdminLTE for demo purposes -->
<script src={{ asset('AdminLTE/dist/js/demo.js') }}></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src={{ asset('AdminLTE/plugins/select2/js/select2.full.min.js') }}></script>

<script src={{ asset('AdminLTE/plugins/moment/moment.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/inputmask/jquery.inputmask.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/bootstrap-colorpicker/js/bootstrap-colorpicker.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/bootstrap4-duallistbox/jquery.bootstrap-duallistbox.min.js') }}></script>

{{-- tabledata --}}
<script src={{ asset('AdminLTE/plugins/datatables/jquery.dataTables.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/datatables-bs4/js/dataTables.bootstrap4.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/datatables-responsive/js/dataTables.responsive.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/datatables-responsive/js/responsive.bootstrap4.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/datatables-buttons/js/dataTables.buttons.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/toastr/toastr.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/datatables-buttons/js/buttons.bootstrap4.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/jszip/jszip.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/pdfmake/pdfmake.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/pdfmake/vfs_fonts.js') }}></script>
<script src={{ asset('AdminLTE/plugins/datatables-buttons/js/buttons.html5.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/datatables-buttons/js/buttons.print.min.js') }}></script>
<script src={{ asset('AdminLTE/plugins/datatables-buttons/js/buttons.colVis.min.js') }}></script>


{{-- customJS --}}

<script>
    $(function() {
        //Initialize Select2 Elements
        $('.select2').select2();

        //Initialize Select2 Elements
        $('.select2bs4').select2({
            theme: 'bootstrap4'
        })
    })

</script>

resources/views/backend/layouts/head.blade.php
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Ouransoft</title>
  <link rel="shortcut icon" href="https://ouransoft.vn/upload/logo-ouransoft.png">
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,400i,700&amp;display=fallback">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="{!!asset('AdminLTE/plugins/fontawesome-free/css/all.min.css')!!}">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Tempusdominus Bootstrap 4 -->
  <!--Select2-->
  <link rel="stylesheet" href="{!!asset('AdminLTE/plugins/select2/css/select2.min.css')!!}">
  <link rel="stylesheet" href="{!!asset('AdminLTE/plugins/tempusdominus-bootstrap-4/css/tempusdominus-bootstrap-4.min.css')!!}">
  <!-- iCheck -->
  <link rel="stylesheet" href="{!!asset('AdminLTE/plugins/icheck-bootstrap/icheck-bootstrap.min.css')!!}">
  <!-- JQVMap -->
  <link rel="stylesheet" href="{!!asset('AdminLTE/plugins/jqvmap/jqvmap.min.css')!!}">
  <!-- Theme style -->
  <link rel="stylesheet" href="{!!asset('AdminLTE/dist/css/adminlte.min.css')!!}">
  <!-- overlayScrollbars -->
  <link rel="stylesheet" href="{!!asset('AdminLTE/plugins/overlayScrollbars/css/OverlayScrollbars.min.css')!!}">
  <link rel="stylesheet" href="{!!asset('AdminLTE/plugins/select2-bootstrap4-theme/select2-bootstrap4.min.css')!!}">
  <!-- Toastr -->
  <link rel="stylesheet" href="{!!asset('AdminLTE/plugins/toastr/toastr.min.css')!!}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{!!asset('AdminLTE/plugins/daterangepicker/daterangepicker.css')!!}">
  <!-- summernote -->
  <link rel="stylesheet" href="{!!asset('AdminLTE/plugins/summernote/summernote-bs4.min.css')!!}">
   <link rel="stylesheet" href="{!!asset('AdminLTE/css/custom.css')!!}">
<style type="text/css">/* Chart.js */
@keyframes chartjs-render-animation{from{opacity:.99}to{opacity:1}}.chartjs-render-monitor{animation:chartjs-render-animation 1ms}.chartjs-size-monitor,.chartjs-size-monitor-expand,.chartjs-size-monitor-shrink{position:absolute;direction:ltr;left:0;top:0;right:0;bottom:0;overflow:hidden;pointer-events:none;visibility:hidden;z-index:-1}.chartjs-size-monitor-expand>div{position:absolute;width:1000000px;height:1000000px;left:0;top:0}.chartjs-size-monitor-shrink>div{position:absolute;width:200%;height:200%;left:0;top:0}</style></head>

resources/views/backend/layouts/header.blade.php
<nav class="main-header navbar navbar-expand navbar-white navbar-light">
    <ul class="navbar-nav">
        <li class="nav-item">
            <a class="nav-link" data-widget="pushmenu" href="#" role="button"><i class="fas fa-bars"></i></a>
        </li>
    </ul>
    <ul class='navbar-nav ml-auto'>
        <li class="nav-item">
            <form method="POST" action="{{ route('logout') }}">
            @csrf
            <a class="nav-link" href="{{ route('logout') }}" onclick="event.preventDefault();this.closest('form').submit();">
              <i class="fas fa-sign-out-alt"></i>
              Đăng xuất
            </a>
            </form>
        </li>
    </ul>
</nav>

resources/views/backend/layouts/mess.blade.php
@if (Session::get('success'))
<script>
    toastr.success('{{ Session::get('success') }}')
</script>
@endif

@if (Session::get('error'))
    <script>
        toastr.error('{{ Session::get('success') }}')
    </script>
@endif

@if (Session::get('warning'))
    <script>
        toastr.warning('{{ Session::get('success') }}')
    </script>
@endif

@if (Session::get('info'))
    <script>
        toastr.info('{{ Session::get('success') }}')
    </script>
@endif

resources/views/backend/layouts/sidebar.blade.php
<aside class="main-sidebar sidebar-dark-primary elevation-4">
    <!-- Brand Logo -->
    <a href="https://ouransoft.vn" class="brand-link d-flex logo-admin">
        <img src="{!!asset('AdminLTE/img/logo.png')!!}" alt="Logo" class="brand-image">
    </a>
    <!-- Sidebar -->
    <div class="sidebar os-host os-theme-light os-host-overflow os-host-overflow-y os-host-resize-disabled os-host-transition os-host-scrollbar-horizontal-hidden"><div class="os-resize-observer-host observed"><div class="os-resize-observer" style="left: 0px; right: auto;"></div></div><div class="os-size-auto-observer observed" style="height: calc(100% + 1px); float: left;"><div class="os-resize-observer"></div></div><div class="os-content-glue" style="margin: 0px -8px; width: 249px; height: 204px;"></div><div class="os-padding"><div class="os-viewport os-viewport-native-scrollbars-invisible" style="overflow-y: scroll;"><div class="os-content" style="padding: 0px 8px; height: 100%; width: 100%;">
                    <!-- Sidebar user panel (optional) -->
                    <div class="user-panel mt-3 pb-3 mb-3 d-flex">
                        <div class="image">
                            <img src="{!! Auth::user()->profile_photo_url !!}" class="img-circle elevation-2" alt="{!!Auth::user()->name!!}">
                        </div>
                        <div class="info">
                            <a href="{{route('profile.show')}}" class="d-block">{!!Auth::user()->name!!}</a>
                        </div>
                    </div>
                    <!-- Sidebar Menu -->
                    <nav class="mt-2">
                        <ul class="nav nav-pills nav-sidebar flex-column" data-widget="treeview" role="menu" data-accordion="false">
                            <!-- Add icons to the links using the .nav-icon class
                                 with font-awesome or any other icon font library -->
                            <li class="nav-item">
                                <a href="{!!route('dashboard')!!}" class="nav-link @if(Route::currentRouteName() == 'dashboard') active @endif">
                                    <i class="nav-icon fas fa-tachometer-alt"></i>
                                    <p>
                                        Dashboard
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{!!route('company.index')!!}" class="nav-link @if(Route::currentRouteName() == 'company.index') active @endif">
                                    <i class="nav-icon fas fa-users"></i>
                                    <p>
                                        Quản lý công ty
                                    </p>
                                </a>
                            </li>
                            <li class="nav-item">
                                <a href="{!!route('member.index')!!}" class="nav-link @if(Route::currentRouteName() == 'member.index') active @endif">
                                    <i class="nav-icon fas fa-users"></i>
                                    <p>
                                        Quản lý thành viên
                                    </p>
                                </a>
                            </li>
                            @can('roles-index')
                            <li class="nav-item">
                                <a href="{{route('user.index')}}" class="nav-link @if(Route::currentRouteName() == 'user.index') active @endif">
                                    <i class="nav-icon fas fa-user"></i>
                                    <p>
                                        Quản lý tài khoản
                                    </p>
                                </a>
                            </li>
                            @endcan
                            @can('roles-index')
                            <li class="nav-item">
                                <a href="{{route('roles.index')}}" class="nav-link @if(Route::currentRouteName() == 'roles.index') active @endif">
                                    <i class="nav-icon fas fa-user-shield"></i>
                                    <p>
                                        Quản lý phân quyền
                                    </p>
                                </a>
                            </li>
                            @endcan
                        </ul>
                    </nav>
                    <!-- /.sidebar-menu -->
                </div>
            </div>
        </div>
        <div class="os-scrollbar os-scrollbar-horizontal os-scrollbar-unusable os-scrollbar-auto-hidden">
            <div class="os-scrollbar-track">
                <div class="os-scrollbar-handle" style="width: 100%; transform: translate(0px, 0px);"></div>  
            </div>
        </div>
        <div class="os-scrollbar os-scrollbar-vertical os-scrollbar-auto-hidden">
            <div class="os-scrollbar-track">
                <div class="os-scrollbar-handle" style="height: 15.1069%; transform: translate(0px, 0px);">
                </div>      
            </div>  
        </div>
        <div class="os-scrollbar-corner">
        </div>
    </div>
    <!-- /.sidebar -->
</aside>