routes/frontend.php
<?php
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\AuthController;

Route::get('/register', [AuthController::class, 'getRegister'])->name('home.get-register');
Route::post('/register', [AuthController::class, 'postRegister'])->name('home.post-register');
Route::get('/login', [AuthController::class, 'getLogin'])->name('home.get-login');
Route::get('/forgot-password', [AuthController::class, 'forgotPassword']);
Route::post('/login', [AuthController::class, 'postLogin'])->name('home.post-login');
Route::get('/logout', [AuthController::class, 'logout'])->name('home.logout');

Route::group(['middleware' => 'frontend'], function() {
    Route::get('/', [FrontendController::class, 'index'])->name('home.index');
    Route::get('/home/mbti', [FrontendController::class, 'mbti'])->name('home.mbti');
    Route::get('/home/leadership', [FrontendController::class, 'leadership'])->name('home.leadership');
    Route::get('/home/teamwork', [FrontendController::class, 'teamwork'])->name('home.teamwork');
    Route::get('/home/quick', [FrontendController::class, 'quick'])->name('home.quick');
    Route::get('/home/quick2', [FrontendController::class, 'quick2'])->name('home.quick2');
    Route::get('/home/result-quick', [FrontendController::class, 'resultQuick'])->name('home.quick.result');
    Route::get('/home/result', [FrontendController::class, 'resultMbti'])->name('home.mbti.result');
    Route::get('/home/result-leadership', [FrontendController::class, 'resultLeadership'])->name('home.leadership.result');
    Route::get('/home/result-teamwork', [FrontendController::class, 'resultTeamwork'])->name('home.teamwork.result');
    //end messenger
});

routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\CompanyController;

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::get('/admin', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('admin/user', UserController::class);
    Route::resource('admin/company', CompanyController::class);
    Route::resource('admin/roles', RoleController::class);
    Route::get('/admin/member/index', [MemberController::class, 'index'])->name('member.index');
    Route::delete('/admin/member/delete/{id}', [MemberController::class, 'destroy'])->name('member.destroy');
});

app/Models/Company.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Company extends Model
{
    use HasFactory;
    protected $table = 'company';
    protected $fillable = ['user_id','name','code'];
}

app/Http/Controllers/CompanyController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Repositories\CompanyRepository;

class CompanyController extends Controller
{
    public function __construct(CompanyRepository $companyRepo) {
        $this->companyRepo = $companyRepo;
    }
    public function index(){
        $records = $this->companyRepo->where('user_id',\Auth::user()->id)->get();
        return view('backend.company.index',compact('records'));
    }
    public function create(){
        return view('backend.company.create');
    }
    public function store(Request $request)
    {
        $input = $request->all();
        $input['user_id'] = \Auth::user()->id;
        $input['code'] = time();
        $company = $this->companyRepo->create($input);
        return redirect()->route('company.index')
                        ->with('success','Tạo mới công ty thành công');
    }
    public function edit($id)
    {
        $record = $this->companyRepo->find($id);
        return view('backend.company.edit',compact('record'));
    }
    
    public function update(Request $request, $id)
    {
        $input = $request->all();
        $company = $this->companyRepo->update($id,$input);
        return redirect()->route('company.index')
                        ->with('success','Cập nhật công ty thành công');
    }
    public function destroy($id){
        $company = $this->companyRepo->find($id);
        $company->delete();
        return redirect()->back()->with('success', 'Xóa thành công');
    }
}

resources/views/backend/company/create.blade.php
@extends('backend.layouts.admin')
@section('content')
<section class="content-header">
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>Thêm công ty</h1>
    </div>
    <div class="col-sm-6">
      <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{!!route('dashboard')!!}">Dashboard</a></li>
        <li class="breadcrumb-item active">Quản lý công ty</li>
      </ol>
    </div>
  </div>
</div><!-- /.container-fluid -->
</section>
<div class="card card-primary">
<!-- /.card-header -->
<!-- form start -->
<form action="{!!route('company.store')!!}" method="POST">
    @csrf
  <div class="card-body">
    <div class="form-group">
      <label for="company_name">Tên công ty</label>
      <input type="text" name="name" class="form-control" id="company_name" placeholder="Nhập tên công ty" required="">
    </div>
  </div>
  <!-- /.card-body -->
  <div class="card-footer">
    <button type="submit" class="btn btn-primary">Tạo mới</button>
  </div>
</form>
</div>
@stop
@section('script')
@parent
<script>
  $(function () {
    $('.select2').select2();
  });
</script>
@stop

resources/views/backend/company/edit.blade.php
@extends('backend.layouts.admin')
@section('content')
<section class="content-header">
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>Cập nhật công ty</h1>
    </div>
    <div class="col-sm-6">
      <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{!!route('dashboard')!!}">Dashboard</a></li>
        <li class="breadcrumb-item active">Quản lý công ty</li>
      </ol>
    </div>
  </div>
</div><!-- /.container-fluid -->
</section>
<div class="card card-primary">
<!-- /.card-header -->
<!-- form start -->
<form action="{!!route('company.update',$record->id)!!}" method="POST">
   @method('PUT')
   @csrf
  <div class="card-body">
    <div class="form-group">
      <label for="company_name">Tên công ty</label>
      <input type="text" name="name" class="form-control" id="company_name" value="{!!$record->name!!}" placeholder="Nhập tên công ty" required="">
    </div>
  </div>
  <!-- /.card-body -->
  <div class="card-footer">
    <button type="submit" class="btn btn-primary">Cập nhật</button>
  </div>
</form>
</div>
@stop
@section('script')
@parent
<script>
  $(function () {
    $('.select2').select2();
  });
</script>
@stop

resources/views/backend/company/index.blade.php
@extends('backend.layouts.admin')
@section('content')
<section class="content-header">
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>Quản lý công ty</h1>
    </div>
    <div class="col-sm-6">
      <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{!!route('dashboard')!!}">Dashboard</a></li>
        <li class="breadcrumb-item active">Quản lý công ty</li>
      </ol>
    </div>
  </div>
</div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-header text-right">
                        <a class="btn btn-primary" href="{!!route('company.create')!!}"><i class="nav-icon fas fa-plus-circle text-white"></i> Thêm mới</a>
                    </div>
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Tên công ty</th>
                                    <th>Mã code</th>
                                    <th>Ngày tạo</th>
                                    <th>Tác vụ</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($records as $key=>$record)
                                <tr>
                                    <td>{!! ++$key !!}</td>
                                    <td>{!! $record->name !!}</td>
                                    <td>{!! $record->code !!}</td>
                                    <td>{!! date('d/m/Y',strtotime($record->created_at)) !!}</td>
                                    <td class="d-flex ">
                                        <a class='btn text-blue px-1' href="{!!route('company.edit',$record->id)!!}"><i class="nav-icon fas fa-edit"></i></a>
                                        <form action="{{ route('company.destroy', $record->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn px-1">
                                               <i class="nav-icon fas fa-trash-alt text-red"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
@stop
@section('script')
@parent
<script>
  $(function () {
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
@stop