routes/frontend.php
<?php
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\AuthController;

Route::get('/register', [AuthController::class, 'getRegister'])->name('home.get-register');
Route::post('/register', [AuthController::class, 'postRegister'])->name('home.post-register');
Route::get('/login', [AuthController::class, 'getLogin'])->name('home.get-login');
Route::get('/forgot-password', [AuthController::class, 'forgotPassword']);
Route::post('/login', [AuthController::class, 'postLogin'])->name('home.post-login');
Route::get('/logout', [AuthController::class, 'logout'])->name('home.logout');

Route::group(['middleware' => 'frontend'], function() {
    Route::get('/', [FrontendController::class, 'index'])->name('home.index');
    Route::get('/home/mbti', [FrontendController::class, 'mbti'])->name('home.mbti');
    Route::get('/home/leadership', [FrontendController::class, 'leadership'])->name('home.leadership');
    Route::get('/home/teamwork', [FrontendController::class, 'teamwork'])->name('home.teamwork');
    Route::get('/home/quick', [FrontendController::class, 'quick'])->name('home.quick');
    Route::get('/home/quick2', [FrontendController::class, 'quick2'])->name('home.quick2');
    Route::get('/home/result-quick', [FrontendController::class, 'resultQuick'])->name('home.quick.result');
    Route::get('/home/result', [FrontendController::class, 'resultMbti'])->name('home.mbti.result');
    Route::get('/home/result-leadership', [FrontendController::class, 'resultLeadership'])->name('home.leadership.result');
    Route::get('/home/result-teamwork', [FrontendController::class, 'resultTeamwork'])->name('home.teamwork.result');
    //end messenger
});

routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\CompanyController;

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::get('/admin', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('admin/user', UserController::class);
    Route::resource('admin/company', CompanyController::class);
    Route::resource('admin/roles', RoleController::class);
    Route::get('/admin/member/index', [MemberController::class, 'index'])->name('member.index');
    Route::delete('/admin/member/delete/{id}', [MemberController::class, 'destroy'])->name('member.destroy');
});

app/Http/Controllers/RoleController.php
<?php
    
namespace App\Http\Controllers;


use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Spatie\Permission\Models\Role;
use Spatie\Permission\Models\Permission;
use DB;
    
class RoleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    function __construct()
    {
         $this->middleware('permission:roles-index|roles-create|roles-edit|roles-delete', ['only' => ['index','store']]);
         $this->middleware('permission:roles-create', ['only' => ['create','store']]);
         $this->middleware('permission:roles-edit', ['only' => ['edit','update']]);
         $this->middleware('permission:roles-delete', ['only' => ['destroy']]);
    }
    
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $records = Role::orderBy('id','DESC')->paginate(5);
        return view('backend.roles.index',compact('records'));
    }
    
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $records = Permission::get();
        return view('backend.roles.create',compact('records'));
    }
    
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required|unique:roles,name',
            'permission' => 'required',
        ]);
    
        $role = Role::create(['name' => $request->input('name')]);
        $role->syncPermissions($request->input('permission'));
        return redirect()->route('roles.index')
                        ->with('success','Tạo mới quyền thành công');
    }
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $role = Role::find($id);
        $rolePermissions = Permission::join("role_has_permissions","role_has_permissions.permission_id","=","permissions.id")
            ->where("role_has_permissions.role_id",$id)
            ->get();
    
        return view('backend.roles.show',compact('role','rolePermissions'));
    }
    
    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $role = Role::find($id);
        $records = Permission::get();
        $rolePermissions = DB::table("role_has_permissions")->where("role_has_permissions.role_id",$id)
            ->pluck('role_has_permissions.permission_id','role_has_permissions.permission_id')
            ->all();
    
        return view('backend.roles.edit',compact('role','records','rolePermissions'));
    }
    
    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'permission' => 'required',
        ]);
    
        $role = Role::find($id);
        $role->name = $request->input('name');
        $role->save();
    
        $role->syncPermissions($request->input('permission'));
    
        return redirect()->route('roles.index')
                        ->with('success','Cập nhật quyền thành công');
    }
    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::table("roles")->where('id',$id)->delete();
        return redirect()->route('roles.index')
                        ->with('success','Xóa quyền thành công');
    }
}

resources/views/backend/roles/create.blade.php
@extends('backend.layouts.admin')
@section('content')
<section class="content-header">
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>Thêm quyền</h1>
    </div>
    <div class="col-sm-6">
      <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{!!route('dashboard')!!}">Dashboard</a></li>
        <li class="breadcrumb-item active">Quản lý quyền</li>
      </ol>
    </div>
  </div>
</div><!-- /.container-fluid -->
</section>
<div class="card card-primary">
<!-- /.card-header -->
<!-- form start -->
<form action="{!!route('roles.store')!!}" method="POST">
    @csrf
  <div class="card-body">
    <div class="form-group">
      <label for="exampleInputEmail1">Tên quyền</label>
      <input type="text" name="name" class="form-control" id="exampleInputEmail1" placeholder="Nhập tên quyền" required="">
    </div>
    <label>Danh sách quyền</label>
    <div class="form-group">
      @foreach($records as $key=>$record)
      <div class="custom-control custom-checkbox">
        <input class="custom-control-input" name='permission[]' type="checkbox" id="customCheckbox{!!++$key!!}" value="{!!$record->id!!}">
        <label for="customCheckbox{!!$key!!}" class="custom-control-label form-check-label">{!!$record->name!!}</label>
      </div>
      @endforeach
    </div>
  </div>
  <!-- /.card-body -->

  <div class="card-footer">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>
</div>
@stop

resources/views/backend/roles/edit.blade.php
@extends('backend.layouts.admin')
@section('content')
<section class="content-header">
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>Cập nhật quyền</h1>
    </div>
    <div class="col-sm-6">
      <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{!!route('dashboard')!!}">Dashboard</a></li>
        <li class="breadcrumb-item active">Quản lý quyền</li>
      </ol>
    </div>
  </div>
</div><!-- /.container-fluid -->
</section>
<div class="card card-primary">
<!-- /.card-header -->
<!-- form start -->
<form action="{!!route('roles.update',$role->id)!!}" method="POST">
    @method('PUT')
    @csrf
  <div class="card-body">
    <div class="form-group">
      <label for="exampleInputEmail1">Tên quyền</label>
      <input type="text" name="name" class="form-control" id="exampleInputEmail1" placeholder="Nhập tên quyền" required="" value='{!!$role->name!!}'>
    </div>
    <label>Danh sách quyền</label>
    <div class="form-group">
      @foreach($records as $key=>$record)
      <div class="custom-control custom-checkbox">
        <input class="custom-control-input" name='permission[]' type="checkbox" id="customCheckbox{!!++$key!!}" value="{!!$record->id!!}" @if(in_array($record->id, $rolePermissions)) checked @endif>
        <label for="customCheckbox{!!$key!!}" class="custom-control-label form-check-label">{!!$record->name!!}</label>
      </div>
      @endforeach
    </div>
  </div>
  <!-- /.card-body -->

  <div class="card-footer">
    <button type="submit" class="btn btn-primary">Submit</button>
  </div>
</form>
</div>
@stop

resources/views/backend/roles/index.blade.php
@extends('backend.layouts.admin')
@section('content')
<section class="content-header">
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>Quản lý quyền</h1>
    </div>
    <div class="col-sm-6">
      <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{!!route('dashboard')!!}">Dashboard</a></li>
        <li class="breadcrumb-item active">Quản lý quyền</li>
      </ol>
    </div>
  </div>
</div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <div class="card-header text-right">
                        <a class="btn btn-primary" href="{!!route('roles.create')!!}"><i class="nav-icon fas fa-plus-circle text-white"></i> Thêm mới</a>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Tên quyền</th>
                                    <th>Ngày tạo</th>
                                    <th>Tác vụ</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($records as $key=>$record)
                                <tr>
                                    <td>{!! ++$key !!}</td>
                                    <td>{!! $record->name !!}</td>
                                    <td>{!! date('d/m/Y',strtotime($record->created_at)) !!}</td>
                                    <td class='d-flex'>
                                        <a class='btn text-blue px-1' href="{!!route('roles.edit',$record->id)!!}"><i class="nav-icon fas fa-edit"></i></a>
                                        <form action="{{ route('roles.destroy', $record->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn px-1" >
                                               <i class="nav-icon fas fa-trash-alt text-red"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
@stop
@section('script')
@parent
<script>
  $(function () {
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
@stop