routes/frontend.php
<?php
use App\Http\Controllers\FrontendController;
use App\Http\Controllers\AuthController;

Route::get('/register', [AuthController::class, 'getRegister'])->name('home.get-register');
Route::post('/register', [AuthController::class, 'postRegister'])->name('home.post-register');
Route::get('/login', [AuthController::class, 'getLogin'])->name('home.get-login');
Route::get('/forgot-password', [AuthController::class, 'forgotPassword']);
Route::post('/login', [AuthController::class, 'postLogin'])->name('home.post-login');
Route::get('/logout', [AuthController::class, 'logout'])->name('home.logout');

Route::group(['middleware' => 'frontend'], function() {
    Route::get('/', [FrontendController::class, 'index'])->name('home.index');
    Route::get('/home/mbti', [FrontendController::class, 'mbti'])->name('home.mbti');
    Route::get('/home/leadership', [FrontendController::class, 'leadership'])->name('home.leadership');
    Route::get('/home/teamwork', [FrontendController::class, 'teamwork'])->name('home.teamwork');
    Route::get('/home/quick', [FrontendController::class, 'quick'])->name('home.quick');
    Route::get('/home/quick2', [FrontendController::class, 'quick2'])->name('home.quick2');
    Route::get('/home/result-quick', [FrontendController::class, 'resultQuick'])->name('home.quick.result');
    Route::get('/home/result', [FrontendController::class, 'resultMbti'])->name('home.mbti.result');
    Route::get('/home/result-leadership', [FrontendController::class, 'resultLeadership'])->name('home.leadership.result');
    Route::get('/home/result-teamwork', [FrontendController::class, 'resultTeamwork'])->name('home.teamwork.result');
    //end messenger
});

routes/web.php
<?php

use App\Http\Controllers\DashboardController;
use App\Http\Controllers\UserController;
use App\Http\Controllers\RoleController;
use App\Http\Controllers\MemberController;
use App\Http\Controllers\CompanyController;

Route::middleware(['auth:sanctum', 'verified'])->group(function () {
    Route::get('/admin', [DashboardController::class, 'index'])->name('dashboard');
    Route::resource('admin/user', UserController::class);
    Route::resource('admin/company', CompanyController::class);
    Route::resource('admin/roles', RoleController::class);
    Route::get('/admin/member/index', [MemberController::class, 'index'])->name('member.index');
    Route::delete('/admin/member/delete/{id}', [MemberController::class, 'destroy'])->name('member.destroy');
});

app/Models/User.php
<?php

namespace App\Models;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;
use Laravel\Fortify\TwoFactorAuthenticatable;
use Laravel\Jetstream\HasProfilePhoto;
use Laravel\Sanctum\HasApiTokens;
use Spatie\Permission\Traits\HasRoles;

class User extends Authenticatable
{
    use HasApiTokens;
    use HasFactory;
    use HasProfilePhoto;
    use Notifiable;
    use TwoFactorAuthenticatable;
    use HasRoles;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $table = 'users';   
    protected $guard_name = 'sanctum';
    protected $fillable = [
        'name',
        'email',
        'password',
        'code',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password',
        'remember_token',
        'two_factor_recovery_codes',
        'two_factor_secret',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    /**
     * The accessors to append to the model's array form.
     *
     * @var array
     */
    protected $appends = [
        'profile_photo_url',
    ];
    
    public function company(){
        return $this->hasMany('\App\Models\Company');
    }
}

app/Http/Controllers/UserController.php
<?php

namespace App\Http\Controllers;
use Illuminate\Http\Request;
use App\Repositories\UserRepository;
use Spatie\Permission\Models\Role;
use Illuminate\Support\Facades\Hash;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Arr;

class UserController extends Controller
{
    public function __construct(UserRepository $userRepo) {
        $this->userRepo = $userRepo;
        $this->middleware('permission:user-index|user-create|user-edit|user-delete', ['only' => ['index','store']]);
        $this->middleware('permission:user-create', ['only' => ['create','store']]);
        $this->middleware('permission:user-edit', ['only' => ['edit','update']]);
        $this->middleware('permission:user-delete', ['only' => ['destroy']]);
    }
    public function index(){
        $records = $this->userRepo->all();
        return view('backend.user.index',compact('records'));
    }
    public function create(){
        $roles_html = \App\Helpers\StringHelper::getSelectOptions(Role::all());
        return view('backend.user.create',compact('roles_html'));
    }
    public function store(Request $request)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email',
            'password' => 'required|same:confirm-password',
            'roles' => 'required'
        ]);
        $input = $request->all();
        $input['password'] = Hash::make($input['password']);
        $input['code'] = Hash::make(time());
        $user = $this->userRepo->create($input);
        $user->assignRole($request->input('roles'));
        return redirect()->route('user.index')
                        ->with('success','Tạo mới tài khoản thành công');
    }
    public function edit($id)
    {
        $record = $this->userRepo->find($id);
        $userRole = $record->roles->pluck('id')->all();
        $roles_html = \App\Helpers\StringHelper::getSelectOptions(Role::all(),$userRole);
        return view('backend.user.edit',compact('record','roles_html'));
    }
    
    public function update(Request $request, $id)
    {
        $this->validate($request, [
            'name' => 'required',
            'email' => 'required|email|unique:users,email,'.$id,
            'password' => 'same:confirm-password',
            'roles' => 'required'
        ]);
        $input = $request->all();
        if(!empty($input['password'])){ 
            $input['password'] = Hash::make($input['password']);
        }else{
            $input = Arr::except($input,array('password'));    
        }
    
        $user = $this->userRepo->find($id);
        $user->update($input);
        DB::table('model_has_roles')->where('model_id',$id)->delete();
        $user->assignRole($request->input('roles'));
        return redirect()->route('user.index')
                        ->with('success','User updated successfully');
    }
    public function destroy($id){
        $user = $this->userRepo->find($id);
        $user->delete();
        return redirect()->back()->with('success', 'Xóa thành công');
    }
}

resources/views/backend/user/create.blade.php
@extends('backend.layouts.admin')
@section('content')
<section class="content-header">
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>Thêm tài khoản</h1>
    </div>
    <div class="col-sm-6">
      <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{!!route('dashboard')!!}">Dashboard</a></li>
        <li class="breadcrumb-item active">Quản lý tài khoản</li>
      </ol>
    </div>
  </div>
</div><!-- /.container-fluid -->
</section>
<div class="card card-primary">
<!-- /.card-header -->
<!-- form start -->
<form action="{!!route('user.store')!!}" method="POST">
    @csrf
  <div class="card-body">
    <div class="form-group">
      <label for="exampleInputEmail1">Họ tên</label>
      <input type="text" name="name" class="form-control" id="exampleInputEmail1" placeholder="Nhập tên quyền" required="">
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Email</label>
      <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Nhập email" required="">
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Mật khẩu</label>
      <input type="password" name="password" class="form-control" id="exampleInputEmail1" placeholder="Nhập mật khẩu" required="">
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Xác nhận mật khẩu</label>
      <input type="password" name="confirm-password" class="form-control" id="exampleInputEmail1" placeholder="Nhập lại mật khẩu" required="">
    </div>
    <div class="form-group">
        <label>Quyền</label>
        <select class="form-control select2" name="roles[]" data-placeholder="Chọn quyền" style="width: 100%;" multiple="">
          {!!$roles_html!!}
        </select>
    </div>
  </div>
  <!-- /.card-body -->
  <div class="card-footer">
    <button type="submit" class="btn btn-primary">Tạo mới</button>
  </div>
</form>
</div>
@stop
@section('script')
@parent
<script>
  $(function () {
    $('.select2').select2();
  });
</script>
@stop

resources/views/backend/user/edit.blade.php
@extends('backend.layouts.admin')
@section('content')
<section class="content-header">
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>Cập nhật tài khoản</h1>
    </div>
    <div class="col-sm-6">
      <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{!!route('dashboard')!!}">Dashboard</a></li>
        <li class="breadcrumb-item active">Quản lý tài khoản</li>
      </ol>
    </div>
  </div>
</div><!-- /.container-fluid -->
</section>
<div class="card card-primary">
<!-- /.card-header -->
<!-- form start -->
<form action="{!!route('user.update',$record->id)!!}" method="POST">
    @method('PUT')
    @csrf
  <div class="card-body">
    <div class="form-group">
      <label for="exampleInputEmail1">Họ tên</label>
      <input type="text" name="name" class="form-control" id="exampleInputEmail1" placeholder="Nhập tên quyền" value="{!!$record->name!!}" required="">
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Email</label>
      <input type="email" name="email" class="form-control" id="exampleInputEmail1" placeholder="Nhập email" value="{!!$record->email!!}" required="">
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Mật khẩu</label>
      <input type="password" name="password" class="form-control" id="exampleInputEmail1" placeholder="Nhập mật khẩu">
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1">Xác nhận mật khẩu</label>
      <input type="password" name="confirm-password" class="form-control" id="exampleInputEmail1" placeholder="Nhập lại mật khẩu">
    </div>
    <div class="form-group">
        <label>Quyền</label>
        <select class="form-control select2" name="roles[]" data-placeholder="Chọn quyền" style="width: 100%;" multiple="">
          {!!$roles_html!!}
        </select>
    </div>
  </div>
  <!-- /.card-body -->
  <div class="card-footer">
    <button type="submit" class="btn btn-primary">Cập nhật</button>
  </div>
</form>
</div>
@stop
@section('script')
@parent
<script>
  $(function () {
    $('.select2').select2();
  });
</script>
@stop

resources/views/backend/user/index.blade.php
@extends('backend.layouts.admin')
@section('content')
<section class="content-header">
<div class="container-fluid">
  <div class="row mb-2">
    <div class="col-sm-6">
      <h1>Quản lý tài khoản</h1>
    </div>
    <div class="col-sm-6">
      <ol class="breadcrumb float-sm-right">
        <li class="breadcrumb-item"><a href="{!!route('dashboard')!!}">Dashboard</a></li>
        <li class="breadcrumb-item active">Quản lý tài khoản</li>
      </ol>
    </div>
  </div>
</div><!-- /.container-fluid -->
</section>
<section class="content">
    <div class="container-fluid">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <!-- /.card-header -->
                    <div class="card-header text-right">
                        <a class="btn btn-primary" href="{!!route('user.create')!!}"><i class="nav-icon fas fa-plus-circle text-white"></i> Thêm mới</a>
                    </div>
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr>
                                    <th>STT</th>
                                    <th>Họ tên</th>
                                    <th>Email</th>
                                    <th>Ngày tạo</th>
                                    <th>Tác vụ</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach($records as $key=>$record)
                                <tr>
                                    <td>{!! ++$key !!}</td>
                                    <td>{!! $record->name !!}</td>
                                    <td>{!! $record->email !!}</td>
                                    <td>{!! date('d/m/Y',strtotime($record->created_at)) !!}</td>
                                    <td class="d-flex ">
                                        <a class='btn text-blue px-1' href="{!!route('user.edit',$record->id)!!}"><i class="nav-icon fas fa-edit"></i></a>
                                        <form action="{{ route('user.destroy', $record->id) }}" method="POST">
                                            @csrf
                                            @method('DELETE')
                                            <button class="btn px-1">
                                               <i class="nav-icon fas fa-trash-alt text-red"></i>
                                            </button>
                                        </form>
                                    </td>
                                </tr>
                                @endforeach
                            </tbody>
                        </table>
                    </div>
                    <!-- /.card-body -->
                </div>
            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
@stop
@section('script')
@parent
<script>
  $(function () {
    $('#example2').DataTable({
      "paging": true,
      "lengthChange": false,
      "searching": false,
      "ordering": true,
      "info": true,
      "autoWidth": false,
      "responsive": true,
    });
  });
</script>
@stop